version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost:9090'

  grafana:
    image: grafana/grafana-enterprise:latest
    restart: always
    user: root
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

  node_exporter:
    image: prom/node-exporter
    restart: always
    ports:
      - '9100:9100'
  # vega_master:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
