{
 "title": "my monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "different usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1-sum(irate(node_cpu_seconds_total{mode=\"idle\"}[2m]))by(instance)/sum(irate(node_cpu_seconds_total[2m]))by(instance))*100",
     "legendFormat": "notIdle - {{instance}}"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\"}[2m]))by(instance)/sum(irate(node_cpu_seconds_total[2m]))by(instance)*100",
     "legendFormat": "iowait - {{instance}}"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[2m]))by(instance)/sum(irate(node_cpu_seconds_total[2m]))by(instance)*100",
     "legendFormat": "system - {{instance}}"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[2m]))by(instance)/sum(irate(node_cpu_seconds_total[2m]))by(instance)*100",
     "legendFormat": "user - {{instance}}"
    }
   ]
  },
  {
   "title": "different cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[2m])",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "current node number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_num_total" }
   ]
  },
  {
   "title": "vega running time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vega_seconds_total" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vega_stage", "legendFormat": "{{stage}}" }
   ]
  },
  {
   "title": "different nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-((sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m]))by(instance))/sum(rate(node_cpu_seconds_total[2m])) by(instance)))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}