name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: rustup override set nightly-2023-04-17-x86_64-unknown-linux-gnu | cargo build --verbose
    - name: Run tests
      run: cargo test --verbose